---
pagetitle: "Yueh-ya (Sam) Hsu"
title-prefix: ""
description-meta: "PhD candidate at the University of Chicago Harris School of Public Policy researching refugee welfare in developing countries through randomized field experiments in Bangladesh and Uganda."
---

## About

I am a PhD candidate at the [Harris School of Public Policy](https://harris.uchicago.edu/) at the University of Chicago. My research studies refugee welfare in developing countries, using randomized field experiments. My current work includes projects in Bangladesh and Uganda.

My work would not be possible without data collection and implementation partners like [RTM](https://rtm-international.org/index/), [IGREC](https://igrec-ug.org/), and [Hofokam](https://hofokam.co.ug/).

## Research

### Working Papers

- [**Household Preferences for Women's Employment: A Field Experiment in Bangladesh**](files/employment_on_partnerships.pdf) (with [Reshmaan N. Hussam](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=952941), [Erin M. Kelley](https://www.erinmunrokelley.com/), and [Gregory Lane](https://www.gregoryvlane.com/)). *Submitted.* [[NBER WP](https://www.nber.org/papers/w34969)] [[UNHCR Policy Brief](https://www.unhcr.org/media/bangladesh-policy-brief-impact-livelihood-activities-among-rohingya-refugees)]

### In Progress

- [**Is it All About the Work?**](files/all_about_work.pdf) (with [Reshmaan N. Hussam](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=952941), [Erin M. Kelley](https://www.erinmunrokelley.com/), and [Gregory Lane](https://www.gregoryvlane.com/)).

- **Flight Risk or Reward? Returns to Credit Between Refugees and Locals** (with [Sylvan Herskowitz](https://www.sylvanherskowitz.com/), [Reshmaan N. Hussam](https://www.hbs.edu/faculty/Pages/profile.aspx?facId=952941), [Erin M. Kelley](https://www.erinmunrokelley.com/), and [Gregory Lane](https://www.gregoryvlane.com/)). *Data collection underway.*
